### ISSUE TITLE
executable size

### ISSUE THREAD

**Issue by albmac** [gordoste/openprog_tools#4]
Both op and opgui have nearly doubled in size compared to the last version.
In case of opgui it could be due to gtk3, but op should stay the same as it is command-line and nearly unchanged.
I tried removing gtk libs from compile command but it did not make any difference.

**Comment by gordoste** [comment]
I had a look at the symbol table using objdump and couldn't see any duplication. Will need to find a more sophisticated tool.

**Comment by albmac** [comment]
After a lot of trials I found that it is all due to the compilation flags: in the final link phase the following are missing: -Os -s
