### ISSUE TITLE
Response time for changing device family is quite long

### ISSUE THREAD

**Issue by gordoste** [gordoste/openprog_tools#5]
Selecting any family seems to take 1-5 seconds - not great, but tolerable. Selecting `*` seems to create significant CPU load and takes >30 seconds. One potential workaround could be to remove the `*` family.

**Comment by albmac** [comment]
I tried to set the combo width to 0 before adding elements, then back to 6 at the end.
Great improvement in speed.
in 
void FilterDevType(GtkWidget *widget,GtkWidget *window)
	gtk_combo_box_set_wrap_width(GTK_COMBO_BOX(devCombo),0);
	... 
	combo populate code 
	...
	gtk_combo_box_set_wrap_width(GTK_COMBO_BOX(devCombo),6);

**Comment by gordoste** [comment]
Awesome! I made this change. I tried hiding the combo box while populating it, but that didn't work.
